

###
GET http://localhost:12321/proxy/blockchain.atomicals.listscripthash?params=[%22a98d3e974bdf9488520ce83ea14fbdb55878e73c8be79ddd38749cc742b3ea40%22,true]

###
POST http://localhost:12321/proxy/blockchain.atomicals.listscripthash
Content-Type: application/json

{
  "params": [
    "a98d3e974bdf9488520ce83ea14fbdb55878e73c8be79ddd38749cc742b3ea40",
    true
  ]
}

###
GET http://localhost:12321/proxy

###
GET http://localhost:12321